apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vnc-gateway-cf-warp-secret
  namespace: smt-prod
spec:
  encryptedData:
    WIREGUARD_ADDRESSES: AgCkmCLZMpooCcfPx4CPsmUnNX/iYSl/qARW4Cd7beC1bjaYPl73xIvsN66EA1hbxSlpUL3AL7o5NtOm+Re8jxzESMBxZYVf1XO6PzGPS8qVn9o+xbgUSns2IRqU6bw7JP2jhVmRmuYWjMe2cqoGob19JMJb3cLn8/1C5RwhJbziv8qYuWkbRviUV3uMQtTAfOa38+TVGYcDKMsEkglH1PznhX8GaYy7MYEHtrMvRPMo8JQj5Up1M1V0Bl5BB/tbrkfYkVX4wP8ws2z1j6ZumHNqHUcYStD0dCmq8vkg58udOTIWVwb/brqiEPBsQuoZTVOAdhV+S1e1nHh8ank8KMuTZSzF9Fu/PNnpeECN07ERcUjiddXpHmGIxMxwmo2IrSWt5GQF5dZ8WYV05BcHSWCEJUqNBrPIGgOO2+CIYCRCG6pcGNz43gskWEka8k1wy0IyVy5hO7wRDvckOVZrv9JvGTJsFCZsn+neGnDnQmIX+B9X+TzIRg0G/LBrYPOuRE1OLgrznnnzQgCRSMOBQWSBQgdjIFck0gJbHW9mFVIMUkO+0UJ/OWSe0TUGvbIT4va+U1XefSp/uUC+48/8KS4Ogl4z+Z0yULHRJr/d6BICpo4LBGLaN0veG6sxUXXnB5SxKbEYPaDh8GSlvY9/5qvLQKv2hV3rNWqcHCpjsNRzAWxcwxYjAQ6yMMoBUCQOesOrIdJ7O9hVvxF6T0xS
    WIREGUARD_PRIVATE_KEY: AgADq86Ak1iMXjIJzPyePdhQStObkPPReDSpHvb3/a7Du+fjPtle9cEfOyrgy+WgCMIQMT0DcCDtS7WrX3M8Nt/xh4bJf89MFotaTK2ygyvpEBlQ+acKk03r+KUhq/sYE6Yj2JdrLsErA5GktoMm9kAOurirWVoysTHWOxAd0LjBQTUTPtMh3jgxlUYizXBMAc8Vlgd8cILIpzVEvxuAhhH8/5qry4P1m9nK8y4Ew0Yfx7KF0OCA9sdF5AliN0FnweifrCH20ZZujrRO+1jRk4F1N6d93M7k4lkAxTop8jImJaTSCDpfO4+R7lUHMsUTvxTrAU7mmTrDW8UQu95mKm8JcTl8SKHqi4xIJj8wTA0d5GoS/IOJjbC+IVHiE/frchD2t4osSxhQS4akvWqlhQ9HHejrg4vFCm1e7L80O7s5dY2E3F04FmjQeUwQyaRyGPSaFufWIheox+WJWyjBRXULikNftaoLDyNMcpthowJ3vOu67IhAVrSlKZuo2H8jPOelDKLYOcS90gI+VXvdml4Qrm0qMAmu7uTHbpwlU6Hi4DbmWe/52g5YOComNJbubT/xB4OKBAGe5RPHRsGRtqswVvBx4V2C6Zo5AWxAQid8l7L5lQFL47yIT6+nL/ugxeo+e7qQZkX4pWF8HMdOvqQ1bWdYuLA6nn/J5WMGxRyxBB3m4lZtd/U++sacUXY1Wi5ZtFTzC1CZoY0vQ8C5aB2YFuFb4mkN1lmWtuIgyFwwWb++iTeaytZte/Fyiw==
  template:
    metadata:
      name: vnc-gateway-cf-warp-secret
      namespace: smt-prod
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smt-secret
  namespace: smt-prod
spec:
  encryptedData:
    .env: AgAFKfHW6pcwEn8EcCnNGlKuO/wjRo9Z3NVONd2Kbc2mC2z2Vh9VmSKTTxQvbG/Pqj1b5TSv2gNjlKc85Xri0x28hm8nZPh/O2wCXc+A7jbKe+EU7qWIL9AP5YEA9wej4ho3VySExH5YDR7LLxTQdEGoEbtXBo2FSzwjbTYN13Xn+z0doDhN+vZp1hpqBEKbpSgjpP1A0PEDjYVGgMkw4IG03975K3NqkU9uE0LH6bj5iCUTITUXNBigUHHExQ3FvKHLgx3KpZG5NDb5w2B7jLMLsp0jpi2O/jxUa7OlR82mfqTlIv0Rg9jrbTwL7OIXW7eL2DCUs+6IljXxKJkTBkAwPESki0UJKCnZqFCR9z4gMSC7fFy6MklH93udP4wMtTt0KTY0u9PW55Qle+N3inLmBDFW36fzosM05Bn2tyg9/zg1K25i7ySgwpFRlUypPgClxfnSPbvddTIo0GONYitJquY4FbK1tD/X6LNiQ+7yoq+RiU2mBJsHE/sJ5V06mMqgdd2mjfOVjQWwFCDmvarxpW+VejPdBV8TPzmpTog7vbu2r8x3t2ssS5ltd1CgFQ07rQgCJRAJmmV5ULgVNEwpswUTv3RloaTig23ztQJvmp1UY4gGnQ4TZJEXljpLjAVRdltabkue5JGQcAE5NZO1sFcoOCRM1QDacPU+xBapikROAMbkUDdtDxteFO0cYq7x7cHV/TYyzKE3aOA71mSRBDIzB6HzrX7h5qiEMFwGQyXwzN/lR2vm7LdKpMD06Yfgj7pyR3nJ31d2WIvkT99wIW1yxIQ4uUyBnztEOM2GH1/Iv4TpJ4XfJlC27dWaFblvrcMbKLX28Z91M0j/dZMRuRLy7Xh3j65HjcGgZeydlC/yuSWQL++wE+0w9Z0LyAmRluk2xFVGEAr/Ju5KjNfgvJ7HMsJU/qaC/z/SE9OmMBs+tAkDqW10igsQOzOHF+IZybgjqIAj
  template:
    metadata:
      name: smt-secret
      namespace: smt-prod
    type: Opaque
