apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: smt-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "create", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: smt-rolebinding
subjects:
  - kind: ServiceAccount
    name: smt-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: smt-role
