---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vnc-gateway-cf-warp-secret
  namespace: smt-prod
spec:
  encryptedData:
    WIREGUARD_ADDRESSES: AgC2ECwxn+BAMq9FGRldRteCFuTuwCuaHSlVdqJbgSWsf6dlO8nT5S8JZugS1eGDBbOzSycr4a5fFOvn09sdZebLDBIjgIpY45R4HipizWegytEAziLBMHemyqWizXjby+24P2x/IqDsS1w1lg2tPmqi+r9KqMthto0tEvGKHfsxu4IXRY7nbtBGcQG6s5/b/fHuMkK7iDwTnumY6hCriokmpF3na3k3rBnrxONKmkF5qrvPnHMbCuuHo67IqUeg2Z/VCiMs6gVx61DUpl39rxtEQxFTCC7Ggvo1VEzuNPBW5DHWlM9Mf/fqWSSFSJtH8z81C2vThtFHg3g/soVCG/JzVvFpRiQHhxaq0h7TQZufuK9ba0wWeTHkr7fPHqD63hPj9/Bkwcf7J+O4lO8VfwZLdQEsc6eSTaDfFrQUFRoRXZV4e3lnEr1oUjg52cDBwbS64Jd+5szQ0A8069FfFGCFmHn/GWC6+HDbSY8Rs6pl3E5kKp+Qv0+RBcMd3Ydf+6B/bzOHrYNCYgIQoUHP1zgUemKrPBZvMXKrMAA3kgslvGB2/QcHIBQFU+z1K9VAHozM0d3G+gnAMOQRPEPhuxxp51iDkyGRoTdZ2R8INGbp2KM2JL6EC9va2ZX4MuA5erTHzrBoFGlQ2mpFfKRVWp1KbEvtUaBGgFWeWVQ+ycHq40yUIE9mkxPtAmNnLRiWOklc6V6BVKd4T74JuvLy
    WIREGUARD_PRIVATE_KEY: AgCJKxF3RQCuv/FF3NbMYOfE5Ar8wIhac3v5QQ/MYbQmNGP0Pu7skC8VWlvnY14WltzWUow9eEzP+xb+t9ulWvet1hdFE7H+GWQAV5Q0YUcxXTUw+9n7xESNetxeTYvEm8rXbj0hddrGNiJA6YQSXIWb95rrsFGPER2JD1EFSPtuPGUlDvD6PUd3KEuGnJpDqgZ4VYAshnSZqqxvFFmz11TjfZVADY2Qkxop9NGsEI3F/lSVtCjyVV7uJxew7UIVynzxYX7WiEKU30XmueH4JPBVp34drQ0JJB4RHTrnykC9249QUvOV7Mlv40R2Jwv0+BUyrVMe+QXh34DwVTlayoquJrQpj4+/15u550lkrQ1SFo8egdqJL44ozgIxOOU3aKUkKeJRor91Le4uF5BBgJCoS9e5b5QDtscYxFzn82BJ1BbCcC09/yt9Ly7NAQQstnWLS5RKF7YUSnO4CwQh+PLo7ep/xWfQaxIIx3unPy75bw+hjUVvDZOpiyepg9ZcXNge36VPVizRdgyd4bv8bKy4eRfNtk7dZm+X05xuYPRRGYO3qX8/aBrHAEJ6+1fqEkZLHHvYAA1HNzw6Yrp8u4K7Xm4ugiiQk7licepCcKGNkBM9yZ0uHm6XeZWChtiDMuonEvEzj2oOwj7TRPfkOU4UED9tylw5MUX+0hN2/feEaBkTL7gaO1dNA2tPzVYFJyUYUajPXMzo1noHec/Fpj71T60+9nhmEp3/6axKqIwkNFEhvoU46bzbd4+32Q==
  template:
    metadata:
      name: vnc-gateway-cf-warp-secret
      namespace: smt-prod
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smt-secret
  namespace: smt-prod
spec:
  encryptedData:
    .env: AgAoxLS2WnvrePO21L7edApRQhZIsxiKRDYkVNCNI/YsfL7WYGqTHGB9Mhtd/oh/1QB9pXxof4oA3/mjurLd6ZHOarQsfxUxkVOk1cS5gyqvHbctvpdNqz0HT8Dm71M7lSCZ917AgYkGuSZWRMA9XVbt11pyreDOLfI3nBta+ke69cmIXExpRMTBYsFNJawDbD7K8ljhpMI6fPJpKWGlBSfGT5UPo0K8CV4CpgZL1Oy23vuCNaeqcUw+MLqP6nxn6Tlxi4s37tw5MsR1c4qkDlsTXTZRqv4L3ofJH+qpWRfHCb7Nmsk78pyriJBBGjj5aoH7PMrXlOOAqslQ/xNCbVrxWJEc33JWcZhYc/OUuhulf4NNwUa1rY/Ntq+noMWUqOjLOHci4+0ZIRaHsEbd2cMfAeAwafIE2tHiNPx5YeczjZmVkWxoFAXo1D6IVuihfjLvQ2fYTugNjqEOsYaOE5GgD8HUheXvm/SQXgZb+evJPpyUy7+rC/L/izFEq28I33EFM127HjUNEzUIjl/k3lq1ozWlcPBnzTKKKFh/aHNrajOtTphZEAS3W5bfab15O/7poG8LKtgX2eILFCHj0fMmrw/N7cjZmjuYsE2oKjJ3WvHCIXCYz0cDNaRcjYJ5jHB/fn9uQ7OU37NXI/hSyQcKKRekPUDaokabRQEHs5979fTQAdTq/VZ8xbMXz8hIbeRuEttAgbQj79OtGs44ZuSqDVv1dywnDbsQLaxy8WCpEVFd/vrOduf6+WJ8zwrNLW0XnVUkoRQbWy+Hbgibro3hytdY6McNuOiQq1PVc4tz6JNTLXqPJPFrP3iU/lhWtP8zMnDXjqzkEeGIQh4svXvTOWjEW4Z3hEs/0QPE2SrQXG3AY0sSuG3JT5rWhyIQ0atb4r0JLQ7TQb0zv0DPU0AW6Aoxc9lCm9d4IqRu6hspCHmkWx3jJdvAMMtqOXvKQXpAp+UHK/+U
  template:
    metadata:
      name: smt-secret
      namespace: smt-prod
    type: Opaque
