apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-secret-updater
spec:
  schedule: "0 */10 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: ecr-secret-updater-sa
          containers:
            - name: ecr-secret-updater
              image: amazon/aws-cli:2.32.26
              env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              envFrom:
                - secretRef:
                    name: smt-aws-ecr-secret
              command:
                - /bin/sh
                - -c
                - |
                  set -e

                  ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
                  ECR_PASSWORD=$(aws ecr get-login-password --region ${AWS_REGION})

                  kubectl create secret docker-registry ecr-secret \
                    --docker-server=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com \
                    --docker-username=AWS \
                    --docker-password="${ECR_PASSWORD}" \
                    --namespace "${POD_NAMESPACE}" \
                    --dry-run=client -o yaml \
                  | kubectl apply -f -
