apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-secret-updater-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-secret-updater-rolebinding
subjects:
  - kind: ServiceAccount
    name: ecr-secret-updater-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecr-secret-updater-role
