apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: sealed-secrets
    releaseName: sealed-secrets
    namespace: kube-system
    repo: https://charts.bitnami.com/bitnami
    version: "2.5.19"
    valuesFile: values/sealed-secrets.yaml

  - name: cert-manager
    releaseName: cert-manager
    namespace: cert-manager
    repo: https://charts.jetstack.io
    version: "v1.19.2"
    valuesFile: values/cert-manager.yaml
