apiVersion: apps/v1
kind: Deployment
metadata:
  name: smt
spec:
  runtimeClassName: kata-qemu-runtime-rs
  template:
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: smt
          imagePullPolicy: IfNotPresent
