---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vnc-gateway-cf-warp-secret
  namespace: smt-local
spec:
  encryptedData:
    WIREGUARD_ADDRESSES: AgCEoiqPxN+JC1gds76GBOfVUL8edR40w8iqjphFH7iqLxE2uxbYadnDdu5uTeJ1IZrQOshYrEoDPAUP6l7gCP54t4VkpYesoI/w2nMNICgVQx416DVrt3HLq33/X8MDbHLVjh9bKNMPNGWTe23hC16MqG6pNRmSXa3HkhRoEPF3onqUmqLFcXUPDOIQyXNAA0AUrYU77lFRLwbIUej2TIxxMBWSmjbLjCCFJc0Gtk7j7FOceMFzVXH2cE9xEfI4MzWDmhPKlPwPIFdExQgElId1CCtYRL+zBE3vmdBEKV9GLF+SUA5vtTFZqtgitN+mQlvEZDFzV6n08h8rJ9NYjb77yCXChjm4H5Jz9PDESAGCMRsIlvkhM7GXOSe/ILNLeg5XKG0uqYHFyVxSshVYCWaDfSKdvqCxRcnomxiDSTawoSmZO581Jp8N1rWoFJAdQbf5Wsu4oLUTbqNL6uZFQQtgyKJOVrQb4/Km7QUhiBfIPApO2QsOUIHdvgOz1jcQ9sW94WWau+3J7Bc9zidQKiOeeeLI0yreGYqS68rCazQgamkoJU32K6LCR921hXbPRh+cJ96f3XOcM18AIvm8W9guzB1fSkJSeNnDhXgC7G6BwQdlbQ/arMmGHtkJSRW7C98200tRqa6XGt6dU4+2I9xienpiPh9GWFilR6fsiJCmZa2m6PB3BjB6cCwznttB1me4e2/WWIlFZsvwj5/V
    WIREGUARD_PRIVATE_KEY: AgBOz4SvRfCH/YoR7i5BVSynWc2sL4z/lNQnaNTLLYPt1pzHsCon5R7rnVVQXyIZwCGGF0/mefpWUhVsw1AFJkFRUOI/JSzYk7yh7FTOmB2+qYpxSR8yajgLvqSUNv33hrFTMHgNJV0SNBk1S3Fs1hlRCd+paUljfT4L8yqjOVG1DEf+InqOYV1szXnwGBPgFXFzRKGERf9OD4XsZpY6P3cbljh9Dty1XXTMpn9MeSyV9auwnNleAee+Hzncv7AL4vU9mpzoOX4mA6orCHCqFT3Ncb6jlt+zA06v1RT7ACeKzk9oDI4sq36auRcK4LMUGmFw8ZR+1PeIm3WB6dmY5pFqslxPpqt8oatIiT5nviCh8K32zHtl+Og8A1dbZXXj+LnszU4DfiVG3nzHD7hB4PuoxNxLIFDas7oU+UEesWGS8fFZZ6rwytiH553h8FGnzNzr2RNaoQiH0gwcOYshcG/Nf+gGokS/0kwsEPrjmrIrluapPlsIBu4qLVNQqXX95GkYgE6n/AgmKmFMPmIdUZ0KGUtuJFWpJt8v96s4U0E749Hn/L6AJFl8NGd68y/9RyFYcXvxwwnl/aeM7VJxS5M6J1HDc0hZ55SmhUIhH1ZuEE25kimxmiLQiN/t6oOMEG9KN1H2HbMOCJw9qknLAxNn7kUh4rx/yT3JKBZHJsunkxHpiAViRuWZ2P0tRx2LywvwTcbnHHZjN5lm5ocXWHK5Alb1B2uL6JXF4xDswM1aev2L8QV40MgpeXcXmw==
  template:
    metadata:
      name: vnc-gateway-cf-warp-secret
      namespace: smt-local
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smt-secret
  namespace: smt-local
spec:
  encryptedData:
    .env: AgBHhKx+UaAA7VTe8fNp1eTrZHdyY/zh3bKS4f9m3OMVsFF1e8zSm0cSbkiJj3dpr+UyP41ULEaI/bpA5BAuL5MB910nrl10MvqZNb8uEBDcTfKS9+ZJXs8Q/Quf3rkWxV7yDW42SNtpx0jWzi92NizBJ4R4yRVFfRzLNK7VU8krDmhHJNXAdoXL1j5GtkEgDanOybjPhqnm98InTjVZ2riDCbbiFLUYmDj1rtfjU0hIxFJAkizhmNhMx7B/woTEgiWpFcUUTP7rTyvUOIACOzQe3QylfkKLkpMmXUM25htkPrYKt1UDVr5crXI8+4RI8xPQSu5MYIrLXpxARv5kB7v08XMj2Q3g+1YvaqGN+Ft0ItZKd3OhbrsTwVKT9CBWr2Okrqn0AunbIEd4Bh1PhnqDLBhOo9vkyKn90VRSzMkBy5ctLnbZ4vYJTeq6yTv9r8UwhuGkPw0CXEzywrU4PbmIZM+vtXmmet+M9/z44jPaLtadtwEzypHPVySKzp8lCeb7W+GSY9YMvBVdY/ocBFH6niPqrEzRZlC4iiaX8+K4495yQvRYDlNIYKEL41BkPu5TlxhP3baaORs6rori+DV3CBgTzKoj6o4vnI8gyo9p3lfiYaF7jRbiw8+q9UEu4ja28KXNtm3DaO4Ey1C1rzXK59JgWeeJFIRvyDNeu00//Dhiw2aC6IkjkOF6YFd6HdRbMXvg2NtgdO5pgulQTqor7N96RiqdQ2DOknCrDz4QKeeH2DrdH1IGO5tH5FgPkFphPcNT4PH9rdYq4yCYHh/SIV9dLU21+cKTDE9QeLvT//g6UM56EqZG6hlnRQ1UO7ic/XhbJ5dYsxJMxyuncBgdXA/TOjm9MNOFN3rbS5WeJmBHz5Ss4REn1LUFBbl+yufmU3mIEsPnCZLXd8rtl7jKdAdv5atfDdMX1HAjE5+UC3yeSpZF2WNz64mtM6Q9dlx3cfQES3rwvuI=
  template:
    metadata:
      name: smt-secret
      namespace: smt-local
    type: Opaque
