apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smt-local

resources:
  - ../../base
  - secrets/sealed-smt-server-secret.yaml

images:
  - name: smt
    newTag: "2.0.0"

  - name: vnc-proxy
    newTag: "1.0.0"
  
  - name: squid
    newTag: "6.13"

configMapGenerator:
  - name: vnc-proxy-cm
    behavior: merge
    literals:
      - K8S_NAMESPACE=smt-local

patches:
  - path: patches/ingress.yaml
      
