controller:
  testEnabled: false

  image:
    tag: 2.528.3-jdk21
  
  admin:
    username: "admin"
    password: "wjstjf97"
  
  jenkinsHome: "/var/jenkins_home"

  serviceType: NodePort
  nodePort: 32000

  resources:
    requests:
      cpu: "100m"
      memory: "1028Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"
    
  runAsUser: 1000
  fsGroup: 1000

  JCasC:
    enabled: true
    defaultConfig: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: "Welcome to SMT Jenkins"

persistence:
  enabled: true
  size: "20Gi"
  accessMode: "ReadWriteOnce"

agent:
  enabled: true
  image:
    repository: "jenkins/inbound-agent"
    tag: "3355.v388858a_47b_33-2-alpine-jdk21"
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
