---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vnc-gateway-cf-warp-secret
  namespace: smt-dev
spec:
  encryptedData:
    WIREGUARD_ADDRESSES: AgCBqPE8/aOtlpqe7QNZCJRVlCbTfFY1tDwAHLu61lhdYJ+p/JP8cEZDEYQFDGydKWibE1ub7kWg3Qm5hTC2tWnpOs2IiXEsoHJINCMIRS2wXsmqnGnULk6vCl5pIfz0WE1ZOOAivDQi45fHstmOC39/ZoIDFrP6pyLBA559TX9BRgwedlhFlJBXpSdZ/aobRyEjnikgB0dsVx5wECmlg31TZt182cQfJIkfwCzuIIk1ygipqh1B1CvZVMlN0nj0jEKDESsOtFlxavLMTkmOL0IyzorLPZfU4hfGmUXxiXLcJR6/iZQOAY1tjCtdCp/Y5PHhzwNpa79AarueU6ijWIa5NzuInuesruAPn+d/zvlrm3BTQieYJ3oIzMLVqhZ/WxcSTBPKrrZmyQkCx511pv0UusBSTqwWXGQ5SmEXZoz1vBvieenU+8P4EizC85TC6lusal3ft4t5sM+3ZvwfR0P0Rj2UEmyhfUlcmzoVdle4JqsFIsjcuO0j7nropOCkRc3nWPIjON4DhzIC4myTBilAY9wK2wp2IWrkyGIhhuKcvISN/LQd5wlehv2Iz4BeiSqVrtAy29WZEf/eCMTbmpiK89X2Csjq/pRZyRLXHO6/nK/Ull7u2WU17N+ErOoa31y+b+GI1wClK5oDdJxAbWEA8JBE/GKWpIcnQIDwwlmc6slQxblbkQsSXxV79nxXl39l6COMGw1zzrzS6DwC
    WIREGUARD_PRIVATE_KEY: AgBQn5nKcW1ge2iTnDDYbTrYrnEgY1SzcVOoG+kJbxgGfo3gyVhBGKcyMQRcG51xp/jYh2yJe/++J7DHb/W2hyn17fge32EOdBIOUGA83tRsg6djZ8SW07vO6OUPryi7uOJ+FMv4h4x21ev3HczZXM7g63G1XqYmNg3Cw/GV+DHxr/bKvgmQCQ5mwfcu+4FgLN2AKGGUemk5oUqK0V5JDwTsek24COyiOsX/KlX738EwpicQxxUU25AkYOLXmvHJc7xJbCsakvbZS81HBj1XyH0KCpxRO6HSTZb7p8spQXPCHxy1A6d0WtR0wEVXKV/xpCBT2BNodMntvyHxeu2E6FeQPdQxLG0q7GE/eEeVa4So2BFqspGW0z8Di/FGEhA9NP1ckEKPSDxEcoCnqJD/2DFss0PG3JNfsipR/IGnmpTj/+VLH/W+dlLpetv5XTikgi1OsVwp0WPibcRZBqLNaZVE4fqidQCjY1HPh5TxZU/FAJ3m++3xNVkwtDJQw1uXIpuXW/EktDN84dok4t+q7ocEkX+1SXr29bR6Xn/EWA4XW8RcY06a1WOrKTyeupEqhSK7BAaTrQwQfvR0A6VLzsQVznNZPEtZiQEajb0sQRVEOBsBdHbSNgqcc1ERQhOGDAw7N9CUoCt+GwYXT02FjcihD+zDRULUhUKaT5v7nXDgPGE1gunVLKRD3OkG7UGFHMu9Q61JbVVSzOrNFRNz1pJQLkGQEWkmfZOO0TO5ouAg9hnm7Y1xSS4inTCMDA==
  template:
    metadata:
      name: vnc-gateway-cf-warp-secret
      namespace: smt-dev
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smt-server-secret
  namespace: smt-dev
spec:
  encryptedData:
    .env: AgCJK4kts9aIvVHM42U2ZPIS6yDAeOUHxxdd88RFHbW5GgeInlZNroXG28RK+GUl7D+eMK/PFShqGGCm6wythr6p1098z0kK8BAbq1DyaCcmm/P3MdzAHlNfyhEyUYvgIq/aeuTmEv+HbN1mn/kiD6V6MImTx0YNugrrVN4Jzi1sZg2JwMQBfk3WpCsZhNWplGO3/bDXk+ef4142qU7T8r2l5c6o1ZjJZyyfY7doLnuenZpuU665dOulSxmYCXNb7aU4PKPyo98GGFkIwsAEcYa7qKbO+g8Iuw5flAo8SMoLXJvE5NfOYfE6J1pOeeZFS+j0XNKaPBQ3w0D9tYtxM/R+2FwyhVN8baQjXpkLki3ycPrkWZ/dkrg4vUk8J/mLUM58yzfiHeZ6wY7UDz5WJv4Gn/skSTKiheqk4xcBvdS5mWpKcwAUmfQwifBmHpPBiTr/7C9GdS8rmvQY6F0BT1gbDJqSotAeeBeNOGhyd350Pr2yNBWwh0var/gACAlRQN1ICtbHomuNF8EYVkgR6k0yz9B51uWhJxjse7kWjWLY+iqBz7vPpESNgc7w+cT91TEZU4QiGqLZ2ue7hCJAHg0OGTBToUJGOjqto/Hsov1yIG9fWnd3LT+iR2Epthwdlpgqe4CtG+F/zT31OV97jZLS/hvjk47WN8YCja3DTfG8NXRKjC4COWBt6cxoiCtPewa0J/HsEdjQXZC2Gq7VkwQNqeAgxGvPhfE1we47UTmJR2emsyODCBALreJOAe1vq8Q16rFnuKWSgqFEJ8QNWDmdZVHDz5zsDiHVCC6nXZMxJFeK2bhDKzAJUaK55CHXwndzkGfx7BwzXORjUPuhhs3WPlu8YVBt9GdbcoSWusqCG6zzzldWjlH4slV++QjCbCLRrlvkx3DdAUSn+XRfrtbajvKnTSqADHmCqmboCt6i+0nYZjzBbpj53a7QINpTOg4kPU4/lfFr
  template:
    metadata:
      name: smt-server-secret
      namespace: smt-dev
    type: Opaque
