---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vnc-gateway-cf-warp-secret
  namespace: smt-dev
spec:
  encryptedData:
    WIREGUARD_ADDRESSES: AgCTx+SA8KteEveCnmOwzCoUb4ApPds1gCxmOfboyOiWohxL93NeJTKGk+GNpzwBi/xo07uAyDkrBZh/UqtibS3u2x7CDezqtaU9+KJgNlumHg42f3meRUZC5wxRN9gwur/hm00tdvyh6UX2pftmHLLQJ7H0D13TtxkXz5JESmn6GSEyf5C/vPj/mlba5Ma2sljjVk2FiDIxaohx8DK9OMCDqYPAPTzLoxRXYn0+fuWmeOoxuDD9dRtvJud3Vgss6mhXohByu8MQY98GPcNVPfM8uU/HPESfKvQegAUJowmraigTc3dTyWnG93qcNv8roZiIn1zwrtPn7Qt+qISRDsYWt/WR28w4QlBeEUWc94+sheXkCvJNqo7UQ02Cb3+GR4nhAc34J7PO1lgH1UH2xWkrudm4dCIXrfo+SJfUIdm+DKUn8w7eJ9tsoE3bUs7Br3y+LJ4RV3unr9WIrOAEPvyVLXZORcTtJzKzZt83/ZmJUFLtiOoANiVsJaUcR81tLwmk9H4p5MHCuAWB9zZscDDqL2eqYD/PmfbjWDkD5K4uSZcCwONa3D5PSUn/5dDAl699kwPPShdksaOjI7Lzu3wndxI11PMPXIVJaF8OWs5Bi5j8LWeM+sYJFeW3l9O1YAw8729lQjetclsv4UhKOQaX2cI6bFxC5avU+HyfYCV6X46Tc9PJIAtPel28MYxVm5eIiw8jveWdi5CIdwUk
    WIREGUARD_PRIVATE_KEY: AgCKfnRJpn5kES0rbMmTOJT2fIXCc9dRQQai1avfsQ73J8DQbQuMNhqAiAkfTeewwOVNd6MFMhAsI5tEl+jixnAMsgKjjerdUOa7G5Y9yT0bYepDIw5wQE+1WXSAO6lHOJOF6MB5q/ue/qve6Ylusn6orEJscXCSAGGPDKA2Z57F9+NacwWNbV7R4QVwerobqHTYMbsqNZdRv1OsSquqO9MxCadY8BztI+Ln3YSKmKV3Cb/7i0SejL9eB5yaQDEYQT3u2VCOGq/UWmx6ACP7TaYf8/MJQuvPphN90lN5wfrKzLbywZx84s2muNwXj5YVxaXOahXat/3nzsktbirWLRNu3bzllpGOZoTYEgzyCwR0b7qhKTBOsMZkwIhDiT12DeEArNB27Nn0eQlvg71DbkpEyg6lzOLxJcmXl3IsKlHgJz3yuBHVZb2fcDP+y+TPW8iPefxARBzw2xAId1qp7qCG0n0WqY53YVIWsHORisvydXlmhUOYfOn8S9xUZtsfeVV6BS50Kp1uHi/6vHRIsdw0Uy9TiSDqFYu0gzUvvTfdHFhwN+EHjNiq7Js5hWrQMPl57J4DyD7Ggu24k/3rZX6+zh8x664ovkg5NCM+dWSkSJ5pBpMcaIN0gtHpIa7VHFA3mERTPm56fKrCAn3Egsed2wiqsN+p0xaETop7V8jUGvm1lt/Z2ojMLtO2UrcSl5mNF4uJatTl3wK3bPbkP/HqqNSbt6PPb1j1N+ue9c03ZK+XvrKcOw4LkeKQfw==
  template:
    metadata:
      name: vnc-gateway-cf-warp-secret
      namespace: smt-dev
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smt-server-secret
  namespace: smt-dev
spec:
  encryptedData:
    .env: AgAPvskcRZ+QjkJh6XauQ2kDH7+Yd66G+CnfUhBlZ1LQFJS667YAj3DQd9Nda6UBkZ74tMqE8EquLUmeb3T5C92HH8rM1IqAEjxVUxVFWDGtSsJJCxMofDcc8DcSuGxeUb8ThIh/qCGlEblC9uopo8ACcjEVT0O4PVzl0lqEbxXlYgOy6rXKYIDdFfCIO1/bWofIcwNMFUK2o+PUr/Uxmwuwm7W2T6x5Km5LPKFmdIiz4Ama3H6Csv6AFSQQpBhqaqH4pTe+rLuyDrPTy83Z+XwV15PIFzC1RmAqjsdAW3DGS+3Fo0u360Gu0gbKk6CbymvhsRJD294UUoLdITdt0K1GV6Qs2dQnmvldkskuNtaWS621KR63pCv9BI4ODmYySii8NiA1CKD5Yxj5HbSoZnqg2M4pvOuYaA1rlZfZa6dSZnAW6iO0PF7h8CMKQnMHJvRWg5ihmi98i6e35QvL+TKLYwffgncDYj+SCDj/eO5KOUoVgFv4LTu6Oq6kfsW9RnYr884bfGsE8qscRhRxPS90fpknyvgSx/GZcoDEdCAN9meHLrbEbIiBUf2oU8xe41cLoa0yTJeEVVUbwQ8gLDfMVnf6u/tIzv+sjngd7eSIA8+C0XdtOjzJVIiz06501QI92cYyzNyF3ud6dH6hnYV9ZiVzQnLsCJJkwYyQbg203qoKfmvDeutlMwXEI1pgP7bpS6tkTx7YBUjg+wZx6GBNa3L8/GUDWsH/MDRLn+9Xk+Vsy/KcXHdFg6JguyzLy3k5undj9/G4slVMo57jt4TnU+Wur9WBoHpHGyd4sFL0aetrRvXIF08/7n/Ub0qj18o03FA9npd+02n4lzWKxlUvWqB25k6Hk7rn+Dt1datvbMt2QMZQGRCcUU9aYfJx6bEv4dLLEd3mnfcuSDXiwfmABuxhxrV6F4yzCsiIpJF6laua1JmGWgNUfhOzrhKfCo6yWG+ILMR1P99YVHCe1yT/2nQLATnD/PL8Fn/P9K4jATNfUDeWlagzS7hc6tTpmCzjgCzoj7Sj5+w=
  template:
    metadata:
      name: smt-server-secret
      namespace: smt-dev
    type: Opaque
