---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vnc-gateway-cf-warp-secret
  namespace: smt-dev
spec:
  encryptedData:
    WIREGUARD_ADDRESSES: AgCBqPE8/aOtlpqe7QNZCJRVlCbTfFY1tDwAHLu61lhdYJ+p/JP8cEZDEYQFDGydKWibE1ub7kWg3Qm5hTC2tWnpOs2IiXEsoHJINCMIRS2wXsmqnGnULk6vCl5pIfz0WE1ZOOAivDQi45fHstmOC39/ZoIDFrP6pyLBA559TX9BRgwedlhFlJBXpSdZ/aobRyEjnikgB0dsVx5wECmlg31TZt182cQfJIkfwCzuIIk1ygipqh1B1CvZVMlN0nj0jEKDESsOtFlxavLMTkmOL0IyzorLPZfU4hfGmUXxiXLcJR6/iZQOAY1tjCtdCp/Y5PHhzwNpa79AarueU6ijWIa5NzuInuesruAPn+d/zvlrm3BTQieYJ3oIzMLVqhZ/WxcSTBPKrrZmyQkCx511pv0UusBSTqwWXGQ5SmEXZoz1vBvieenU+8P4EizC85TC6lusal3ft4t5sM+3ZvwfR0P0Rj2UEmyhfUlcmzoVdle4JqsFIsjcuO0j7nropOCkRc3nWPIjON4DhzIC4myTBilAY9wK2wp2IWrkyGIhhuKcvISN/LQd5wlehv2Iz4BeiSqVrtAy29WZEf/eCMTbmpiK89X2Csjq/pRZyRLXHO6/nK/Ull7u2WU17N+ErOoa31y+b+GI1wClK5oDdJxAbWEA8JBE/GKWpIcnQIDwwlmc6slQxblbkQsSXxV79nxXl39l6COMGw1zzrzS6DwC
    WIREGUARD_PRIVATE_KEY: AgBQn5nKcW1ge2iTnDDYbTrYrnEgY1SzcVOoG+kJbxgGfo3gyVhBGKcyMQRcG51xp/jYh2yJe/++J7DHb/W2hyn17fge32EOdBIOUGA83tRsg6djZ8SW07vO6OUPryi7uOJ+FMv4h4x21ev3HczZXM7g63G1XqYmNg3Cw/GV+DHxr/bKvgmQCQ5mwfcu+4FgLN2AKGGUemk5oUqK0V5JDwTsek24COyiOsX/KlX738EwpicQxxUU25AkYOLXmvHJc7xJbCsakvbZS81HBj1XyH0KCpxRO6HSTZb7p8spQXPCHxy1A6d0WtR0wEVXKV/xpCBT2BNodMntvyHxeu2E6FeQPdQxLG0q7GE/eEeVa4So2BFqspGW0z8Di/FGEhA9NP1ckEKPSDxEcoCnqJD/2DFss0PG3JNfsipR/IGnmpTj/+VLH/W+dlLpetv5XTikgi1OsVwp0WPibcRZBqLNaZVE4fqidQCjY1HPh5TxZU/FAJ3m++3xNVkwtDJQw1uXIpuXW/EktDN84dok4t+q7ocEkX+1SXr29bR6Xn/EWA4XW8RcY06a1WOrKTyeupEqhSK7BAaTrQwQfvR0A6VLzsQVznNZPEtZiQEajb0sQRVEOBsBdHbSNgqcc1ERQhOGDAw7N9CUoCt+GwYXT02FjcihD+zDRULUhUKaT5v7nXDgPGE1gunVLKRD3OkG7UGFHMu9Q61JbVVSzOrNFRNz1pJQLkGQEWkmfZOO0TO5ouAg9hnm7Y1xSS4inTCMDA==
  template:
    metadata:
      name: vnc-gateway-cf-warp-secret
      namespace: smt-dev
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smt-server-secret
  namespace: smt-dev
spec:
  encryptedData:
    .env: AgAif6XnFhntGQY61ZmGLl32C6w7t4VJhvdg37tot+UG8iURkj7+sol8ysmM4PDL07sE9e2GStXVtqpWBiUuxHa24nUR0enZPVLnDxEaWnOkbYTudt75B7qUxE1Ey+MK/ZB1qA1oPvq5qh36+YAht0IVzXWaq7fLvyxHgPUzkneHbSjX9lPfb0H4ULrbpN/i5cQvH9Okjx5r3pnq1x6/xZmma7g82JAziywKCRvDX8hr5stW2cOF3igfKl0BKCLPtQv4+vACKdze2G1Uyy+aLdCMY2nnBrRKxyZbqoVkIdsTEu9Ffk4LXvyH5a9MfhsgbpYSGJEuAvMZ4CyOokeesvoCcV4C9cDhk3u3GZ6slOuBYUJH7aXAHo7iLsnqLq/6ZbUmBZQkkBsqUlo3iO90n7pQ5htv+XDCAlyy6klB5X5MAp+rUvImUzH3EnhdYF+EvILionK+KJWvxyw3StrLEVITcUPAtdZHYmb8E+ojrkEZ/otEQEZ6ryLfrf/fxuSMnUmL/muMkG4UL/oib6Mhfc12g1fQOkePfKTAr1B4Mf4ufO0YiMQ0DivHoD5+/jI+zwck3Oqgcw4ZlCc0oiE1+t1uU1fsqTQND5pnenUp/gbUVqbeN5dJtby/N7RrBDk8NcYjq5XOurHlNtyIRLoMPHJnB01oYS0FbsGDYRf+2ol1oHziLaLgMpfrods5wlrt9/luRyl+5MB7JIYWQsQLHxlr6geA0odoo6HIYercplARWoXHS0XXnyuYQaVQtSbW0fXDI0n20wCf6wF0yYz/spCrheDGaC1r0gttZJI/lPQK06RrJb4k2ogvb5fS4fZ3d935usOTXJFzJP6yzjvFo2KrHee0XiCtibLowTVlADkF+cEVHxFVtYo0HUG5pnhGtq5Tw2K7GGV395K6+d/bPGvmGQsgWHY5TiMPqpzBWhfrehkHl0+/DvO07VWMmqhmsK7zVfcwfzqK
  template:
    metadata:
      name: smt-server-secret
      namespace: smt-dev
    type: Opaque
