---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vnc-gateway-cf-warp-secret
  namespace: smt-prod
spec:
  encryptedData:
    WIREGUARD_ADDRESSES: AgCk+fPjF6BARzE4bmwyJg6iidD/ZiZB0pDgMeQAFZqgytksSv1h26BJzcOFASzoBi1cXfYvIX6apfs4MkNZRTUg9IWHqt+gLueQi2UMRa0PGlhEQ8sILPRsATIgFU8xpdkmK4ezM5twMfymi6ZZu9WVTTZ6u+Gi/yrI0AHbYWNnYivCNtx2mTHTHhC+CRY1Cp/KksB/2krQX4gWrwNi4OEOOULzDC0DG/eXIIHbnAF85QX1HGxwRwC4MMzyeLhNAx836jIBMYmWgbJsMqTJXJIr9D3mePzavs+fG5MDvBEKSLINSuW0Gov3+vs0fAP1nCVfWaGTXrPfZeRAKItISAkVnT7esfPj0calwEs4MIYrvPniElV3LFoU5FiVUVVDk6Dhj4oUHodycbeDCXRxHD0yJeqY6qYviGxPPEOLLbVcET01YDgZx1zKXOTzCW8gXAkZUGG7QFx5QWbGwXionsCa9gRw4MExOqv6UdEjrAiPw/vnFBEf0QuGGDMo4Uz5QZiP9oAWGaGcdbkh02syoupU4o4ZIWxEDwHLrH8Sh3IbOm3u1ztn6BqjrqyhTfFekvGk2/T7/yngqLpAJzleofjDwJSnQh+VGiabUL6VuHGLfmur9ol4Mr5yKsFCbHZsUBx2/jRspS1xrgHN5aucYjRRrqmY92KVupeEe4vBJpbMAgR7kjICcMzx9apuYXhkhYdVwuok07cHTDL7aMnZ
    WIREGUARD_PRIVATE_KEY: AgBJLUILCEvqaxyJaKpuA4TQpZBO/kDuQXvboDAkOTibNIOsI8wR+IMqFabrRE0Aj2Ly1+pCy1bs3w9V2D/um+1dX+KAnBeVuKgvBhVqivdOkORDAQ1gPBdZRCNGKvo4Rw+Nn/CkI6oyB6MxqiYT/hHALagRxLd1+uEEvAnXP6Z8ycQJ7XF+52uByQg+bKdMsloexmOQuRNRVWG53kXBprFkKEdnvXyS+lkAeqkmS16uf5wEl+4yLKkxxu0uN+dB5QxQz5r00mbRP7tsoNwr8IE3Md715z1GrUfb+DZW7UpX9IOe5AJSXuBOjzTpPHskbnlvi7+KZ9pVYaxzo0Ec8axFxL75/4gmNcGZe1oOEFIObLIiFOISk6B8s797LbHOsZNyageoJyl1iKH0qPpDB+4Iav63cB5hPIAPtiZoHV0xZ9CZ2EpiUkuFxlFHGj1jYekki1NDa3W0pkmLKcR2gjRWYb5vc2zdjLXPDaYwnW9slqwBggB5k/BBuznbizXgzRBEH7WYyR/G7rC+GH5M0ys3IT15H7K3KYUkF31P6q3xzhYebqSxhsBlZIa1wyiIf6vPGpi2KhM7BpfYDkwbHSLY0FI3qm1Xle3cgHj+r9KPmXlP7LHYIAKKsKSkzU2oPNdU/xvbwGuvvsAo1RaZGg0Kda4g31bpz7deqMuWVwu3IArzmpzskjRmGbuswRGpgay4w49Eu/G2FjZTgU6WRM9NcJRYLPNc3JyeAmAQ0DTHK9XRN4K7/th2M5+m1Q==
  template:
    metadata:
      name: vnc-gateway-cf-warp-secret
      namespace: smt-prod
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smt-server-secret
  namespace: smt-prod
spec:
  encryptedData:
    .env: AgAYnK6+dflBj12CPrxuqtg3KjrwV/A9Z1R8GOVNkf3C1T5pp8XG5O9NU5waunriDU/DEfUdLkQPzpzar81Q/e/x12Sa0OG0xHQRNq7/HJyZow4naLJ/FejrAIRV1XXUPhJpT6/Bgwkr9rbGEVq0VuuSHVbicujhaKKYYAii4bpgzM/+fVzhV+zLLPbFuJcYA00cUKc4F4HfBkn0nuoTyX68kajvSTbNlfj8sKbHAZ5FS9LScmRXLFlcu7WYOQA4ncwai3E6D8vHutqrHQc+U/2YQ0GmeaMw7XUG4GAiYU4JIE9y0CIdMez3cqggRqkEke4t12QhckUTxOVDazZJnw2VRAbVjGwODC/PCLA/UYdCdGmNHrRvmV87C0KmobeQrC2KOmNZFrpvUKWe4U3vTV6m/aZ5EQ2cfCcDe234qBjK/F/m89bEyZbNK/Qjrf2PQphAZXEqWkzDkKRYF3D+HuLMQqoNX/HV13SYauC+BRQiMCFsKGlN8gQsBBpnlBfRO3GAwD+0aGZ0u7NgJGI9rIDeP83qnXgVmzdDAPeVRsnbApfaIvaBHBrCghbHYasks08V44y47bM/kFR3+rjo6QWVyNw0VBfOmx+VjTUTvbEmc7x7UGl2UHkpzjFyZpTO4iLVuVhzAsP3SNOQk0gsjW7wmOBfMkWHolNSAcRhOuXdjxgjImCgS1qbzuszozEVl7HOF/CgUx0MVOeipXM6F8vZFT3lE/QQUxAdyZQVSdeMSajO1J98di04f2Y+Effd2klMyMmPNaJi7GCsBNpZxsfAmYrX/Fqil7KvjALtXVyRIB9Hyu42V2ygQMIllwSoxVlLaZTmlSDUZWxavBsp2D/4AKdnr56kSPTqftKdaEDBJ91mxI7BygZOYzbubZpc8MWXqK76BoJ2Nx4bLURpddQgQOOlM0a9sELmj9npS6ogujMntmKyomASl8iO66SEtPos+Ctx2dcUxzMxSBkfLsji3OsRI0if9NlXz76II+A16aCYVubzzCYLZqtNsiNT811p+d7T9ZW+SSI=
  template:
    metadata:
      name: smt-server-secret
      namespace: smt-prod
    type: Opaque
