---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vnc-gateway-cf-warp-secret
  namespace: smt-prod
spec:
  encryptedData:
    WIREGUARD_ADDRESSES: AgAAWsplI6BfEzwTd3lrC3Jd0RX1tWzs4xVSjSi3lBqFQUU6SVOYVyfiHjdim4xj+hTO/SVw/9GXx5bJl913b3Wdxf/MXd74JNUbGQOwiHgbEZgvSBPajgtHadnVPe8j+XKXT1EioKUOocDW4DAaf/rztadqZB7SnmMGdVJ5I4YYNaEac0vdxzobkVCTrmrxWDCPry39CaY7wjFZtB63wO/KtcdIGNSsnmBxLFHbENEfQ32e5k3LsXFcN2Vw2cPe847/eTewgaCKmLPLj4LPspt12p7AqDsrFvzrMPsMtnhlSRirNnN2Gmuu12wiu054Jd8S3nA9TfqG/bIohlt4NgnSdTNbK8RvJ4Zg+YtgBwgL8NyzSIWFwjgIc2xz56C+rDBe/E6aYGwS5dTyLJCZYeMwnqB0xTugAnPVXLXy91mHilKb5Fa8w0wSJVNIBNNL6gt2fdarm6M461rmb9TEfzbh4cSikjYvV+duaZG0h3AyF5C9HaqV+P9erSNMmHtEUg72sVpTc3cGelYrEv0MQ9qagEda2N43RejJW6UuSgg143hWKDUquCzYwlB7aXRZCbHKXqaYNTcRwgPsVOqsHpPU5hlWUV4OxG6AIV2DQYpMAaY9PVMvcjisEWSLy+IwbzyW00L4Hu6DGEhyvPk+jzz+XIsFnyC58W/cqwXuMZVBIJ/v1xgbVHahxpoGiJIH2Rmm0nladE7XJPrX/lKd
    WIREGUARD_PRIVATE_KEY: AgDEezi7JkWaSC6/JqgMGpkDTXh3VRxYCfQ0bz6KSq8EZT0rlb0CQ163X1Bl0PQ5iUlykwJYEn9LuYv6pbN4gO8C9tc/nxnFu7Pu8kVC3JegTY/Vq9IhC8F7hzjcMre3OWIaTvEDkE+GzER8pIoI4bmfWk1fIE3aJuG5FlLub+LA7OlzJaEI6++kFItT+YkHjcQAJtT8AOwC11r0twLRhcB38PRLZtYvTG+Z+X10PXZkpz4NwqgWrhql8UglsdkqD1pmGOe+eTfrz4QskbHNodLKnF6xNuP/jTpbZolQQsIlqd7IkBBdh55FSIgpk0CFXy1xU/Yceh6Im7YbxnsNAHjRnX6CXmrdVnWVG+VpBdlsTMeboA49hSew5CoY8xwv/WjTag4OfxJFct/S0bS9loF7EOMuBtiysQujkoT2NowlzLmHSIU+qrJ3zE1LCO8O4q1+a6lEu0zKcP2NxG5BP6tSMIZJ1fIH9VBYACZh6yttzuP2EPJs76iFOLM/kpVhoZqha8yJ7CO5d0YavebqXfegef7D+lBl4rcvJ1ffenO/SJDirDKV4eAMSdN86DThcWpT8qS8hXEBZZ4cQbu57Uhw+L1LkpO55nvE7npO3FmOf0p8Zy2fHeKvIjlINw3Cg+2dI2KoL3CDXm+dV46W4wND81L8vpf/GzzEII/XB1LsQdEyyW3H32ckWGjBq4K1X1PG3wtTIyv2h/y3h0GOZ2l/EGxcofuaPqIddZJ7rf4ywtoHtRk8yMgjsFaicg==
  template:
    metadata:
      name: vnc-gateway-cf-warp-secret
      namespace: smt-prod
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smt-server-secret
  namespace: smt-prod
spec:
  encryptedData:
    .env: AgCm+KrrJZW8DEEIVMXcUkG92in3pbvg+QWK3KBxMzVXPY3ceVSF3J0eGVC21ZIBdfUUWNo9ti3Z2LIOJhdihzNhcfontd6SX7IoDc5UAOA6rmFwd8S/TG4lmJQUwoPge/jUpghM3QCYF9wjeiTNj1Gp4qtt5cnP8QLDmepyeA9KHkdGL6DnJ6OlIorYd1Z0thprQdUpbZju7/jOy0z0BNK062q1JL8l3UlFyIJUmlWayfGb+Z7eItpQlp9t0MwpxszEETWLvi6W12PxE7ABzkYChBz5ypo4OGr9oYxro4KjV4JBHM9hDlK0LqbhI7MNjQv14i7CxF+iSnPjra+2LvV2yhZK3tAZehfpcO4dfBmH8kMBpts5i9d1L9PgyD71ILxHiCEE2XVhWZzypfFLx9fB27VgCUI+WRT+52PSJNr21q1u1Tm39LckDjGh4JdjElf9/Ma/JxNHvT8q3R//YfvtEwFh7d3Fy3++dngQ+GxFV6Ki8PmpjLZUGkgNpleIppyiIPAaV8C0F72bCMm96S8aoJD0sCsuf0BspRZMtQaxEJRMNCQvAN0Q+G/u73wUh8Kl+tSkrk9cDQ6AZRc5ScbSfJLKMOCBqZXPZK83d4rHEkEVxBZ/8Zv1QMreHXiLh/DvRcZ5l1ZJmB442xP87dBglCs1B5tRAHdFQCDdeV/qlZ3DtE4I2L6Iv23A4MVRP7qOrc9pLicKfp57IbIN+6Sglyte4HBXIGoU8zvx461sVOzfz30s3+NN6K3E8mEkuCM5586KHOH8VCGrQIWqqx+4qaXWooSs5wl0SPejFhr/PWNotCFW/m9yoFIee1bBp1vShJlLASMSyPIUfRe90xoddfN6/rhBvWnXEKSaY1ZRrEtffeO9boi31MrKDoGO4yfI9F3m9Z2m/Cwbv6HhAXV+vuX+0hBzxdMuAUDs4lLUK/NlUR2YeGA5vc9byJaf7fk66IigiKYB
  template:
    metadata:
      name: smt-server-secret
      namespace: smt-prod
    type: Opaque
