---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vnc-gateway-cf-warp-secret
  namespace: smt-dev
spec:
  encryptedData:
    WIREGUARD_ADDRESSES: AgAUJiTjZZIfAZ/XbIgH/5JVrKKnq3FpyiABJ8Aoy/lPxL4AXRjAGcrSoZbDgHOwyd7l6HlGCvs8+jOb854TvngkeG5DUHq7y+neARl61EvlK4MoP619Mlhj2+UHGjcXdbAqG3Pk4fmm3kJuPjjGS+SpWMjTtc4fqfN5Unju040OQAY66ZxbDn3A1bYIQLeKY0BokqKo/1zSekUuc4Lml0X2lytvOSkcdu0LNf0j00ihGY6jNerJHaNwuyQBk6DOYzewEHjz/ZiCPo7u0OeNzuk9pjDxrYFQGSERvHfhJCu3Wby0dZhyXRwZksxcBSKA4malo4jvS5X1t9YQ8dhM/Hjc0PFHc1BnjD9CCBUtvXl3cBjLsJYIq7HcR/Qmi0v7A0KTnDGKSBpKoSEiJMN+hyuww0HwfxkhQvyl0Ojhq+GZJ7RfCFqOBiCUIQkMhMecEhRQ7rxtQO4znc1ZhvP+nJBbMuPrq57/zF+8XLI5jFRQDk9AZ0NC4lbiWpCnBtC64ZdzEnzA8HoeTginJiTOju9G0oVVAqswHf88+X0UzEi3xyBBcHD+6gF14E/XXI4ddX0v7Wy/v4mI+1i+9AKlRSzr8beVyGY7u4SXhJt59o5EQGLZ+r4GYTixWAFwXjwLeGgG+dFz1EAh4MMRzEKA/ShZAKajoUlB6yHID0a/YFncYQ5/q/T3g6CAEKWFxxORPsOtFwVZni/FLF9vtOjP
    WIREGUARD_PRIVATE_KEY: AgAO23BUy7uFV3odBZpUitXgfEBtNrCF3/q3uT3VK2hc8qFUvS1abP3gdXQpDdb6NrTmUDn5ri8sqsedx2yFc+yt4LQ7dxkvlHXalTw5UVyDn5q0G0SjAUfqMGv3X8OOAVY/Mev941GAkkC6jOR/zBKbLARnnV8O4CKJLPYOMlwDe/9Q/2+NsldijujRD7PO7jv9IpJzXO2XVAIgaK8OiSywsi8sagP8wR2jnahMKFIq1frS5okVEWMA6ySRQRbN1PhUQUuDDbnyYf/b3Grfgn/Sp5KwoJIKOXfdTLEdxR2Ip4vwInJL1Omr06RnhrhikWgacjXIy9STivsQVfxsToY/Ic9W8Rp2Z6YwETjkGTvZXUKXdu99ar3Fycb36d37wpJvWchqVwQ9LYRAN0Hg4gsmiUkaXx812UYn2KVJZn2ipVHbs+ukdABaWVkvbgT2zlV3Sg8kevzLXqO+CQ9/Faaww2pmOPtGqrRSuAwDhzp6PisrIKS7GjChzX71LM1C/BQ+zmMF6gIZARLD6JErJfo6x2EUjyfIWr2VfO/6AgpaBnFV07SPQbCM9te7jD1arKYrFr810UYomMznHkfTwszqpFusnqq0BydPBCPC44psXxdAwus9mXkXpbFhURD3UM2OdiqBnM9pgfRTwZHZFJeRLYlWpoixPT2WiAZhWELNZhlzzm5NwEVlqLFuday8HpLlD4Eyp5+Yez0jzcmSiaFLplJzXlzVSjFI4ABzm8oF/YuVHNwONmYbelzUew==
  template:
    metadata:
      name: vnc-gateway-cf-warp-secret
      namespace: smt-dev
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smt-secret
  namespace: smt-dev
spec:
  encryptedData:
    .env: AgA93rwEPPOPLEHY3B81dZJA/kHpUhia3SPuNVmTtX17gGwhQsfaNH5WlTJtK2vEXPpGiKaOqgDoUrni+0vvUTol5fABR7ED24wlEjcgcXrXjgxDcWF38z8nwSkctl4BSYdyX7jnKwjZRRbgtyYo8VjOzuvX/TxHx8CQAjG6XOrshNmGIVp/1z2PGbSMKxGADpJ65OpBNLB0yKeMVVtv9rRvXH91ZtJSnYzorUSoszL2pTCjI/xCi8Qne7D/ZjZWqvQSGoKXGo9erq3aKYBkLmabPKijO4SLoQzw1ZRGSVWmj5DzR4eMbRE0VXZ03Id992XZmVHP944exoHgx3Ql45xXjccTwAKj7mEbbM9tQ3U2okoTM9/VhDuglGaoWl/rWYajZrWgnxm171/Pfb5dEnSElQBtHA7Okm5BRso6A8bKJx5N0C/6SFVpClov9l6BzWxjiDmugU3GUunToeZS4XBoUbD0W9wwY6EXZthQaOeKOTe7OWmsi1uz/SCdwJx7BRJXf3IUYzMkxQwGQdz32SACvWnJk1+lxbRgXvNk7xthrxuSBEjdfgHpj0hRbtMIJK5jQSZVTqj6T1FboXgGU1zXVLIuC2OWbibM9CB0v/DWreUmzGZDpsPhMhUq5XdD0OW/uyH4yh7vkfgGwB4lutE929l0NEBM0Nn7q1OLNKqOGW1eTQW9GGrgn7gc2m337kscd5RLI66sI3BnIB1WxOfHXZRaTs9+WwNNlAwpmtNpZT22a/XhDQAu/R3C/QkWVF3Rgs46CkDaTlTp7oNzF91IXeY2bjUMTpbGCNEph3/+iipZ95fc4h5L7BPrwZjNRxceVP1XnUfO4b6kEcFWBCXGpAmckC7c9loguFm/0gb8lb9FmfduPA6JhJEOZ6pl1Kn4gPz/Y7geyo/i5zTZl0Rq54cSNdlix0PRUdKBmFgNSJBk6ScYIFJsT/Zc70M2b8GUDL5AjHFS
  template:
    metadata:
      name: smt-secret
      namespace: smt-dev
    type: Opaque
